<<<<<<< HEAD
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=vitato
    volumes:
      - mongo_data:/data/db
    # Healthcheck uses mongosh (available in official image)
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/vitato
      - JWT_SECRET=change-me
      # Optional for payments (leave blank if not testing)
      - RAZORPAY_KEY_ID=
      - RAZORPAY_KEY_SECRET=
      - RAZORPAY_WEBHOOK_SECRET=
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
=======
version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/vitato
      - JWT_SECRET=change-me
      # Optional for payments (leave blank if not testing)
      - RAZORPAY_KEY_ID=
      - RAZORPAY_KEY_SECRET=
      - RAZORPAY_WEBHOOK_SECRET=
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
>>>>>>> c068d1e (Changed some issues)
