version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitato-app
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      # Safe defaults if .env isn't provided
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/vitato}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID:-}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET:-}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET:-}
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      # Persist uploaded files
      - uploads:/app/public/uploads

  mongo:
    image: mongo:6.0
    container_name: vitato-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  uploads:
